services:
  backend:
    container_name: dreamlabs-challange-backend
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - database
      - pgadmin
    env_file:
      - .env

  pgadmin:
    container_name: dreamlabs-challange-pgadmin
    image: dpage/pgadmin4:8.11
    restart: always
    env_file:
      - .env
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - '5050:80'

  database:
    container_name: dreamlabs-challange-database
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: dreamlabs-challange-database
  pgadmin:
    name: dreamlabs-challange-pgadmin
