services:
  backend:
    container_name: dreamlabs-challange-backend
    build:
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm run start:migrate:dev
    stdin_open: true
    tty: true