version: '3.8'

services:
  database:
    container_name: dreamlabs-challange-database
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    container_name: dreamlabs-challange-backend
    build: .
    ports:
      - '3333:3333'
    depends_on:
      - database
    env_file:
      - .env

volumes:
  postgres:
    name: dreamlabs-challange-database
